### ISSUE TITLE
Private Visualizations (epic)

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#204]
* [X] set visibility from the Settings dialog
* [x] difference in the preview card #206 
* [x] difference in the view page #207
 * [ ] list your own private visualizations  #208
