### ISSUE TITLE
Embedding (epic)

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#209]
* [x] Embedding First Pass #472
 * [ ] Embed in Medium #481
 * [ ] Whitelabel Embedding as part of new paid tier

**Comment by curran** [comment]
Closing in favor of https://github.com/datavis-tech/vizhub-issue-tracker/issues/536
