### ISSUE TITLE
Order Prints (epic)

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#300]
* [ ] "Order Prints" Button in UI
 * [ ] Generation of high resolution screenshots
 * [ ] Collection of order information (address to ship to

**Comment by curran** [comment]
Some examples:
 * https://zachlieberman.myshopify.com/
 * https://www.mapiful.com/
